// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCONbGDmeBM0WvCfw4E4u8uGPwA_8d2m84',
    appId: '1:5316507126:web:8582db862c67d6ce7c43d7',
    messagingSenderId: '5316507126',
    projectId: 'kalkylanalys',
    authDomain: 'kalkylanalys.firebaseapp.com',
    storageBucket: 'kalkylanalys.appspot.com',
    measurementId: 'G-XS83SY6VKQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOqpZbTjnJ_pLs1ir9NzyIXfFOPUFv3zM',
    appId: '1:5316507126:android:225806f8f57d83677c43d7',
    messagingSenderId: '5316507126',
    projectId: 'kalkylanalys',
    storageBucket: 'kalkylanalys.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbsw43Xld2Em3yGqE4v9t957xuW0-oWus',
    appId: '1:5316507126:ios:80e6594baa3b82317c43d7',
    messagingSenderId: '5316507126',
    projectId: 'kalkylanalys',
    storageBucket: 'kalkylanalys.appspot.com',
    iosClientId: '5316507126-393v15hl2lse0ciiooj5a5t8gpskpmhf.apps.googleusercontent.com',
    iosBundleId: 'com.sfaholding.kmaanalys',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbsw43Xld2Em3yGqE4v9t957xuW0-oWus',
    appId: '1:5316507126:ios:80e6594baa3b82317c43d7',
    messagingSenderId: '5316507126',
    projectId: 'kalkylanalys',
    storageBucket: 'kalkylanalys.appspot.com',
    iosClientId: '5316507126-393v15hl2lse0ciiooj5a5t8gpskpmhf.apps.googleusercontent.com',
    iosBundleId: 'com.sfaholding.kmaanalys',
  );
}
